# This file was generated by GoReleaser. DO NOT EDIT.
cask "refuse" do
  version "1.3.4"

  on_macos do
    on_intel do
      sha256 "7536283f6e0598bf88ebe66aa7660b361474574d85cf32d412f536b747f13182"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "097aa3a4187f3db0784573d03c5a405969c9924ad7ecc3aee456503ec4bfbb26"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b6c32d3dcf9da144bd50eef566c19161c19fe828ddccaa2374bae7854aea8a6"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38a12d9fcfe31b6eb47ce4514c7ade9abd6a157b0e569ad7ec6b9ecbe531566a"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_arm64.tar.gz"
    end
  end

  name "refuse"
  desc "PATH shim for npm / pip / cargo / yarn / pnpm / gem / bun / go — refuses to install packages with known CVEs"
  homepage "https://github.com/RefuseHQ/refuse-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refuse"

  # No zap stanza required

end
