# This file was generated by GoReleaser. DO NOT EDIT.
cask "refuse" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "181990748284097ad9fc5d7d751a1cfd7f5cf388d85223add73d1933168a0476"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "58de8558ee4383247e5b3d015c8a1daa6bb0d25b6518472e2e9b74cfdaa1674f"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "021fd15126a64613327006b293519b8e122436cf598d339cd2669e9cd5b43bb3"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "68c6d6ea81be973d2516f82f4bc1cbfb6421c389d80c35b620443e959b6d66bc"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_arm64.tar.gz"
    end
  end

  name "refuse"
  desc "PATH shim for npm / pip / cargo / yarn / pnpm / gem / bun / go — refuses to install packages with known CVEs"
  homepage "https://github.com/RefuseHQ/refuse-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refuse"

  # No zap stanza required

end
