# This file was generated by GoReleaser. DO NOT EDIT.
cask "refuse" do
  version "1.2.3"

  on_macos do
    on_intel do
      sha256 "2ad51ae0b4af6fca5d10f92129e71b69d7c0cea9a0ae6aa08c685e8fddc2206f"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9fc1b450468e61daffd24f2bc5b9898fc72119871a9dabb7b7992c37bd54b6e1"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35fb659a37b9f4dd1ab0e04680c253bfe812817de61214fb76f3d7fe0a114904"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a9bf29e4b49f79e1c25fa4d1720b9f41820032901d6d9088f16c4e85694c5406"
      url "https://github.com/RefuseHQ/refuse-cli/releases/download/v#{version}/refuse_linux_arm64.tar.gz"
    end
  end

  name "refuse"
  desc "PATH shim for npm / pip / cargo / yarn / pnpm / gem / bun / go — refuses to install packages with known CVEs"
  homepage "https://github.com/RefuseHQ/refuse-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refuse"

  # No zap stanza required

end
